source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!


target 'Yodo' do
    
    pod 'SnapKit',          '~> 4.0.0'
    pod 'MonkeyKing',       '~> 1.4.2'
    pod 'SQLite.swift',     '= 0.11.4'
    pod 'CSV.swift',        '~> 2.1.0'
    pod 'ViewAnimator',     '~> 2.0.0'
    pod 'GDPerformanceView-Swift', '~> 1.3.2'
    pod 'SkeletonView', '~> 1.1.1'
    
  target 'YodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
