source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!


target 'Yodo' do
    
    pod 'Alamofire',    '~> 4.5.1'
    pod 'SnapKit',      '~> 4.0.0'
    pod 'Moya’,  	    ‘~> 10.0.0'
   # pod 'RxSwift'
   # pod 'RxCocoa'
    pod 'MonkeyKing',   '~> 1.4.2'
   # pod 'YYWebImage' 
    pod 'Kingfisher', '~> 4.2.0'
    pod 'SQLite.swift', '~> 0.11.4'
    pod 'CSV.swift', '~> 2.1.0'

  target 'YodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
