source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!


target 'Yod' do
    
    # 视图
    pod 'CVCalendar', '~> 1.6.1'
    pod 'GDPerformanceView-Swift', '~> 1.3.2'
    pod 'ViewAnimator',     '~> 2.0.0'
    pod 'SwipeCellKit'
    
    # 工具
    pod 'SnapKit',          '~> 4.0.0'
    pod 'MonkeyKing',       '~> 1.4.2'
    
    # 数据
    pod 'SQLite.swift',     '= 0.11.4'
    pod 'CSV.swift',        '~> 2.1.0'
    pod 'ObjectMapper', '~> 3.1'
    
    
    
  target 'YodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
